language: node_js

sudo: false

node_js:
  - '8'
  - '6' # LTS
  - '4' # LTS

cache:
  directories:
  - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn pre-release
  - yarn test-e2e
